name = "local Ice Flingomatic Bug Fix"
description = "Ice Flingomatic is smarter and works right."
author = "denev"
version = "0.05"
forumthread = ""
api_version = 6
restart_required = false
dont_starve_compatible = false
reign_of_giants_compatible = true
shipwrecked_compatible = true
hamlet_compatible = true
icon_atlas = "modicon.xml"
icon = "modicon.tex"
